### PR TITLE
Add ability to specify additional parameters for the OAuth authentica…

### PR DESCRIPTION
**Pull request by oetkb**
…tion request URL.

Hi Zack...basically, I added the same ability I did in gromit a month or 3 ago.

### CODE REVIEW

**Comment by zgrossbart** [comment]
Is anyone using Spiffy UI now?  The last time I talked to Daniel we didn't have any plans to release a new version of it.  I'm happy to merge in these changes, but who are these changes for and what are the next steps?

**Comment by oetkb** [comment]
Reporting is still using it, and I image that IDMProv is still using it, although I don't know that last for sure. These changes were prompted by me messing with reporting to get it to authentication directly with NAM in the same fashion I did for IG.

As far as next steps...beats me. What did you do before to "release" a version?

**Comment by zgrossbart** [comment]
I'm happy to merge this in.  I think RPT is the only current client.  

We have deploy instructions here:  https://github.com/spiffyui/spiffyui/wiki/MavenPublishCommands

It's a little involved since this deploys to an external Nexus server.  If you want to make it easier you would deploy just to our internal Nexus server.

**Comment by oetkb** [comment]
If by "our" you mean the idmapps server, I imagine that's what I'll do for the SNAPSHOT version. Once we know it all works and are ready for the final build, perhaps publishing it to the external Nexus server would be a good idea.

**Comment by zgrossbart** [comment]
That is funny.  By "ours" I guess I meant "yours".  You can publish the final version to the internal Micro Focus Nexus server  It isn't used outside the company then that's fine and you don't have to worry about generating and publishing new keys.

**Pull request merged**
